apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: xyrm81/nginx-monitoring:latest
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
      - name: exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        ports:
        - name: metrics
          containerPort: 9113
          protocol: TCP
        args: ['-nginx.scrape-uri', 'http://127.0.0.1:80/basic_status']
