apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-svcmon
spec:
  selector:
    matchLabels:
      app: web-svc
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
