apiVersion: apps/v1
kind: Deployment
metadata:
    name: paymentservice
    labels:
        app: paymentservice
spec:
    replicas: 3
    selector:
        matchLabels:
            app: paymentservice
    strategy: 
        type: RollingUpdate
        rollingUpdate: 
            maxUnavailable: 0
            maxSurge: 100%    
    template:
        metadata:
            labels:
                app: paymentservice
        spec:
            containers:
            - name: hipster-paymentservice
              image: xyrm81/hipstershop-paymentservice:v0.0.2
              ports:
                  - containerPort: 34855
              env:
                  - name: PORT
                    value: "34855"
