apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: kube-intro
spec:
  containers:
  - name: web
    image: xyrm81/kube-intro
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: init
    image: busybox:stable
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}  